[package]
name = "myipaddr"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.26" , features = ["json"] }
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
